name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Build Versioning
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Create the package
      run: dotnet pack --configuration Release -p:PackageVersion=${GITVERSION_NUGETVERSIONV2} ./Skyhop.FlightAnalysis/Skyhop.FlightAnalysis.csproj
    - name: Publish the package to NuGet
      run: dotnet nuget push ./Skyhop.FlightAnalysis/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}}
