name: Ship packages

on:
  push:
    branches: [ main, rc/** ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/skyhop/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: dotnet build --configuration Release

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Build Versioning
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Create the package
        run: dotnet pack --configuration Release -p:PackageVersion=${GITVERSION_NUGETVERSIONV2}
      - name: Publish the package to GPR
        run: dotnet nuget push ./artifacts/pkg/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}}
